project:
  type: website
  output-dir: docs

website:
  title: "KejaConnect"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Properties"
        href: props.qmd
      - text: "Houses"
        href: blog.qmd
      - text: "Land"
        href: parcs.qmd
  page-footer:
    center: "© 2025 Ben Amollo"

format:
  html:
    theme: cosmo
    toc: true
    
sidebar:
    - id: blog
      collapse-level: 2
      contents:
        - blog.qmd
        - section: "2025"
          contents: posts/*
